-- ============================================
-- Sprite Atlas Data - Generated by Sprite Converter
-- ============================================

-- Масштаб спрайтов: 0.1250
-- Масштаб изображения: 0.1250
-- Экспортировано спрайтов: 20

local animation = {
    ["gfDance0000"] = {0, 0, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0001"] = {90, 0, 90, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0002"] = {182, 0, 90, 80, frameX=0, frameY=-2, frameWidth=90, frameHeight=82},
    ["gfDance0003"] = {273, 0, 89, 80, frameX=0, frameY=-2, frameWidth=90, frameHeight=82},
    ["gfDance0004"] = {364, 0, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0005"] = {0, 82, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0006"] = {90, 82, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0007"] = {181, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82},
    ["gfDance0010"] = {272, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82},
    ["gfDance0013"] = {363, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82},
    ["gfDance0015"] = {0, 166, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0016"] = {90, 166, 90, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0017"] = {182, 166, 90, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0018"] = {273, 166, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0019"] = {364, 166, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0020"] = {0, 249, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0021"] = {90, 249, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82},
    ["gfDance0022"] = {181, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82},
    ["gfDance0025"] = {272, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82},
    ["gfDance0028"] = {363, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}
}

local atlas_res = {512, 512}

return { animation = animation, resolution = atlas_res}
