-- ============================================
-- Sprite Atlas Data - Generated by Sprite Converter
-- ============================================

-- Масштаб спрайтов: 0.1250
-- Масштаб изображения: 0.1250
-- Всего спрайтов в XML: 30
-- Уникальных спрайтов: 20
-- Экспортировано спрайтов: 30

local frames = {
    -- GFDANCE
    {0, 0, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 1
    {90, 0, 90, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 2
    {182, 0, 90, 80, frameX=0, frameY=-2, frameWidth=90, frameHeight=82}, -- id: 3
    {273, 0, 89, 80, frameX=0, frameY=-2, frameWidth=90, frameHeight=82}, -- id: 4
    {364, 0, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 5
    {0, 82, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 6
    {90, 82, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 7
    {181, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 8
    {181, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 9
    {181, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 10
    {272, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 11
    {272, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 12
    {272, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 13
    {363, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 14
    {363, 82, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 15
    {0, 166, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 16
    {90, 166, 90, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 17
    {182, 166, 90, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 18
    {273, 166, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 19
    {364, 166, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 20
    {0, 249, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 21
    {90, 249, 89, 81, frameX=0, frameY=-1, frameWidth=90, frameHeight=82}, -- id: 22
    {181, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 23
    {181, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 24
    {181, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 25
    {272, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 26
    {272, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 27
    {272, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 28
    {363, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 29
    {363, 249, 89, 82, frameX=0, frameY=0, frameWidth=90, frameHeight=82}, -- id: 30
}

return {frames = frames}
