-- ============================================
-- Sprite Atlas Data - Generated by Sprite Converter
-- ============================================

-- Масштаб спрайтов: 0.2500
-- Масштаб изображения: 0.2500
-- Всего спрайтов в XML: 54
-- Уникальных спрайтов: 44
-- Экспортировано спрайтов: 54

local frames = {
    -- ENTER PRESSED
    {0, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 1
    {251, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 2
    {0, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 3
    {251, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 4
    {0, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 5
    {251, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 6
    {251, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 7
    {0, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 8
    {251, 467, 250, 19, frameX=0, frameY=0, frameWidth=369, frameHeight=19}, -- id: 9

    -- PRESS ENTER TO BEGIN
    {0, 0, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 10
    {0, 22, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 11
    {0, 44, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 12
    {0, 67, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 13
    {0, 89, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 14
    {0, 111, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 15
    {0, 133, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 16
    {0, 156, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 17
    {0, 178, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 18
    {0, 200, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 19
    {0, 222, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 20
    {0, 245, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 21
    {252, 0, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 22
    {252, 22, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 23
    {252, 44, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 24
    {252, 67, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 25
    {252, 89, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 26
    {252, 111, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 27
    {252, 133, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 28
    {252, 156, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 29
    {252, 178, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 30
    {252, 200, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 31
    {252, 222, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 32
    {252, 222, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 33
    {252, 245, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 34
    {252, 178, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 35
    {0, 267, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 36
    {252, 267, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 37
    {0, 289, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 38
    {252, 289, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 39
    {0, 311, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 40
    {252, 311, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 41
    {0, 334, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 42
    {252, 334, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 43
    {0, 356, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 44
    {252, 356, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 45
    {0, 378, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 46
    {252, 378, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 47
    {0, 400, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 48
    {252, 400, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 49
    {0, 423, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 50
    {252, 423, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 51
    {0, 445, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 52
    {252, 445, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 53
    {0, 0, 251, 21, frameX=-1, frameY=0, frameWidth=373, frameHeight=24}, -- id: 54
}

return {frames = frames}
