-- ============================================
-- Sprite Atlas Data - Generated by Sprite Converter
-- ============================================

-- Масштаб спрайтов: 0.2000
-- Масштаб изображения: 0.2000
-- Экспортировано спрайтов: 44

animation = {
    ["ENTER PRESSED0000"] = {0, 374, 200, 15, frameX=0, frameY=0, frameWidth=295, frameHeight=15},
    ["ENTER PRESSED0001"] = {201, 374, 200, 15, frameX=0, frameY=0, frameWidth=295, frameHeight=15},
    ["Press Enter to Begin0000"] = {0, 0, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0001"] = {0, 18, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0002"] = {0, 35, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0003"] = {0, 53, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0004"] = {0, 71, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0005"] = {0, 89, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0006"] = {0, 107, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0007"] = {0, 124, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0008"] = {0, 142, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0009"] = {0, 160, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0010"] = {0, 178, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0011"] = {0, 196, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0012"] = {202, 0, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0013"] = {202, 18, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0014"] = {202, 35, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0015"] = {202, 53, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0016"] = {202, 71, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0017"] = {202, 89, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0018"] = {202, 107, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0019"] = {202, 124, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0020"] = {202, 142, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0021"] = {202, 160, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0022"] = {202, 178, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0024"] = {202, 196, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0026"] = {0, 213, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0027"] = {202, 213, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0028"] = {0, 231, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0029"] = {202, 231, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0030"] = {0, 249, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0031"] = {202, 249, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0032"] = {0, 267, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0033"] = {202, 267, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0034"] = {0, 285, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0035"] = {202, 285, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0036"] = {0, 302, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0037"] = {202, 302, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0038"] = {0, 320, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0039"] = {202, 320, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0040"] = {0, 338, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0041"] = {202, 338, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0042"] = {0, 356, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19},
    ["Press Enter to Begin0043"] = {202, 356, 201, 17, frameX=0, frameY=0, frameWidth=299, frameHeight=19}
}
