-- ============================================
-- Sprite Atlas Data - Generated by Sprite Converter
-- ============================================

-- Масштаб спрайтов: 0.2000
-- Масштаб изображения: 0.2000
-- Экспортировано спрайтов: 4

animation = {
    ["logo bumpin0000"] = {0, 0, 178, 134, frameX=-4, frameY=-3, frameWidth=187, frameHeight=140},
    ["logo bumpin0001"] = {180, 0, 187, 140},
    ["logo bumpin0003"] = {0, 142, 182, 136, frameX=-2, frameY=-2, frameWidth=187, frameHeight=140},
    ["logo bumpin0005"] = {184, 142, 181, 135, frameX=-3, frameY=-2, frameWidth=187, frameHeight=140}
}
