-- ============================================
-- Sprite Atlas Data - Generated by Sprite Converter
-- ============================================

-- Масштаб спрайтов: 0.1250
-- Масштаб изображения: 0.1250
-- Экспортировано спрайтов: 35

bf_death_start = {
    ["bf_death_start_01"] = {0, 0, 54, 55},
    ["bf_death_start_02"] = {55, 0, 54, 55},
    ["bf_death_start_03"] = {111, 0, 54, 55},
    ["bf_death_start_04"] = {166, 0, 54, 55},
    ["bf_death_start_05"] = {222, 0, 54, 55},
    ["bf_death_start_06"] = {277, 0, 54, 55},
    ["bf_death_start_07"] = {333, 0, 54, 55},
    ["bf_death_start_08"] = {388, 0, 54, 55},
    ["bf_death_start_09"] = {444, 0, 54, 55},
    ["bf_death_start_10"] = {0, 56, 54, 55},
    ["bf_death_start_11"] = {55, 56, 54, 55},
    ["bf_death_start_12"] = {111, 56, 54, 55},
    ["bf_death_start_13"] = {166, 56, 54, 55},
    ["bf_death_start_14"] = {222, 56, 54, 55},
    ["bf_death_start_15"] = {277, 56, 54, 55},
    ["bf_death_start_16"] = {333, 56, 54, 55},
    ["bf_death_start_17"] = {388, 56, 54, 55},
    ["bf_death_start_18"] = {444, 56, 54, 55},
    ["bf_death_start_19"] = {0, 112, 54, 55},
    ["bf_death_start_20"] = {55, 112, 54, 55},
    ["bf_death_start_21"] = {111, 112, 54, 55},
    ["bf_death_start_22"] = {166, 112, 54, 55},
    ["bf_death_start_23"] = {222, 112, 54, 55},
    ["bf_death_start_24"] = {277, 112, 54, 55},
    ["bf_death_start_25"] = {333, 112, 54, 55},
    ["bf_death_start_26"] = {388, 112, 54, 55},
    ["bf_death_start_27"] = {444, 112, 54, 55},
    ["bf_death_start_28"] = {0, 168, 54, 55},
    ["bf_death_start_29"] = {55, 168, 54, 55},
    ["bf_death_start_30"] = {111, 168, 54, 55},
    ["bf_death_start_31"] = {166, 168, 54, 55},
    ["bf_death_start_32"] = {222, 168, 54, 55},
    ["bf_death_start_33"] = {277, 168, 54, 55},
    ["bf_death_start_34"] = {333, 168, 54, 55},
    ["bf_death_start_35"] = {388, 168, 54, 55}
}
