-- ============================================
-- Sprite Atlas Data - Generated by Sprite Converter
-- ============================================

-- Масштаб спрайтов: 0.1250
-- Масштаб изображения: 0.1250
-- Экспортировано спрайтов: 12

animation = {
    -- Note Miss Down
    ["bf_note_down_miss_01"] = {0, 0, 47, 49},
    ["bf_note_down_miss_02"] = {47, 0, 47, 49},
    ["bf_note_down_miss_03"] = {95, 0, 47, 49},

    -- Note Miss Left
    ["bf_note_left_miss_01"] = {143, 0, 48, 54},
    ["bf_note_left_miss_02"] = {192, 0, 48, 54},
    ["bf_note_left_miss_03"] = {0, 54, 48, 54},

    -- Note Miss Right
    ["bf_note_right_miss_01"] = {48, 54, 51, 54},
    ["bf_note_right_miss_02"] = {101, 54, 51, 54},
    ["bf_note_right_miss_03"] = {153, 54, 51, 54},

    -- Note Miss Up
    ["bf_note_up_miss_01"] = {206, 54, 47, 55},
    ["bf_note_up_miss_02"] = {0, 111, 47, 55},
    ["bf_note_up_miss_03"] = {47, 111, 47, 55}
}
